from library/python:3.7.3-slim

ENV APP_VERSION=0.0.1
ENV APP_NAME="stockast"

ARG GUNICORN_HOST
ARG GUNICORN_PORT
ARG GUNICORN_WORKERS
ARG GUNICORN_TIMEOUT

# Default environmental variables
ENV STOCKAST_DB_URL="sqlite:////home/python/stockast.db"
ENV STOCKAST_LOG_LEVEL="INFO"
ENV STOCKAST_DATABASE_DEBUG="false"
ENV STOCKAST_IEX_CLOUD_TOKEN=''

ENV PYTHONPATH=/home/python/\
    PYTHONUNBUFFERED=1\
    GUNICORN_HOST=${GUNICORN_HOST:-0.0.0.0}\
    GUNICORN_PORT=${GUNICORN_PORT:-80}\
    GUNICORN_WORKERS=${GUNICORN_WORKERS:-4}\
    GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT:-30}

ADD ./stockast/requirements.txt /home/python/requirements.txt
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc python-dev \
    && pip install --upgrade pip \
    && pip install --no-cache-dir -r /home/python/requirements.txt \
    && apt-get purge -y --auto-remove gcc python-dev

WORKDIR /home/python
ADD ./get-historical-stock-data.py /home/python
ADD ./get-realtime-stock-data.py /home/python
ADD ./stockast /home/python/stockast

# add wait-for-it.sh
COPY ./bin/wait-for-it.sh /home/python
RUN chmod +x /home/python/wait-for-it.sh

EXPOSE 80
CMD gunicorn -b ${GUNICORN_HOST}:${GUNICORN_PORT} --workers ${GUNICORN_WORKERS} stockast.app
