version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-ui
    ports:
      - 80:80
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    command:
        - /home/python/wait-for-it.sh
        - mysql:3306
        - --
        - gunicorn
        - -b
        - 0.0.0.0:80
        - --workers
        - "1"
        - stockast.app
    ports:
      - 8000:80
    environment:
      - STOCKAST_LOG_LEVEL=DEBUG
      - STOCKAST_IEX_CLOUD_TOKEN=${STOCKAST_IEX_CLOUD_TOKEN}
      - STOCKAST_DATABASE_URL=mysql://stockast:stockast@mysql:3306/stockast
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=stockast
      - MYSQL_DATABASE=stockast
      - MYSQL_USER=stockast
      - MYSQL_PASSWORD=stockast
